---
title: "Spread of Wheat Stripe Rust in an Experimental Framework"
subtitle: "Deriving a model for source detection"
author:   
  - name: Trent VanHawkins
    affiliations:
      - ref: osu
    degrees: MS
    corresponding: true
  - name: Christopher Mundt
    affiliations:
      - ref: osu
    degrees: PhD
  - name: David Gent
    affiliations:
      - ref: usda
      - ref: osu
    degrees: PhD
  - name: Shirshendu Chatterjee
    affiliations:
      - ref: nyu
  - name: Sharmodeep Bhattacharyya
    affiliations:
      - ref: osu
    degrees: PhD
affiliations:
  - id: osu
    name: Oregon State University
  - id: usda
    name: U.S. Department of Agriculture
  - id: nyu
    name: City University of New York
format: 
  pdf:
    geometry: "margin=0.75in"
    mathspec: true
    cap-location: bottom
    tbl-cap-location: bottom
    header-includes: 
      - \usepackage{fancyhdr, amsthm, amssymb,amsfonts,amsthm, mystyle, amsmath, bbm}
      - \usepackage{float, tabularx}
      - \floatplacement{table}{H}
      - \pagestyle{fancy}
      - \fancyhead[R]{Model Considerations}
      - \fancyhead[L]{Trent VanHawkins}
      - \fancyfoot[C]{\thepage} # Center page number at bottom of each page
page-layout: full
execute: 
  eval: true
references: references.bib
bibliography: references.bib
---

# Introduction

Previous reports in this series have derived and documented a model for the aerial dispersal of  Stripe Rust (*Puccinia striiformis*) among Wheat plants. In these reports, we explored various model formulations and optimization strategies of a forward-model of disease intensity, which we breifly review here in addition to experimental design.

Now that we have optimized the parameter vector $\boldsymbol\theta_{t,s,b}$ for each transition $t$ in each treatment-replicate combination (indexed by $s$ and $b$, respectively), our goal is to derive and implement a backward model which will allow us to infer the likely contributions of each plant or group of plants to observed disease severity. That is, if we let disease intensity of plant $i$ and time $t$ be denoted by $y_{i,t}$, we would like to derive a model for $y_{i,t-1} | y_{i,t}$. Here, we propose a latent-variable approach for the structure and optimization of such a model via the Expectation-Maximization (EM) algorithm. 

# Methods

We have detailed experimental design rigerously in previous reports (see "00_EDA.qmd"), but let us recall that we index disease severity $Y$  at an individual sample location $i$ at time $t \in \bigpar{1, \ldots, 5}$ by $Y_{i,t}$. Additionally, we can denote the experimental block $b \in (1, 2, 3, 4)$, with replicates distinguished by the number of inoculation sources (treatment-levels) $s \in \bigpar{1, 2, 4}$. Recall that disease severity at sample location $i$ was measured via visual estimation as the proportion of infected plant tissue within a $(0.76m \times 0.76m)$ square, and was expressed as a percentage. Using this measurement scheme, the outcome naturally presents as a continuous measure with bounds at $(0,1)$, which is naturally captured by a $\text{Beta}(a, b)$ distribution where $a$ and $b$ are shape parameters. That is,

$$
Y_{i,t,s,b} \overset{\text{indep.}}{\sim} \text{Beta}(a_{i,t,s,b},b_{i,t,s,b}).
$$

In this report, as in previous reports, we will drop subscripts for block and replicate ($b$ and $s$) for economy of expression. We reparameterize the model such that its expectation is its mean $\mu_{i,t}$. The density function for a single observation of $y_{i,t}$ is then given by 

$$
f(y_{i,t} \mid \mu_{i,t}, \phi_t) = \frac{\Gamma(\phi_t)}{\Gamma(\mu_{i,t} \phi_t)\Gamma((1 - \mu_{i,t})\phi_t)} \cdot y^{\mu_{i,t}\phi_t - 1}(1 - y)^{(1 - \mu_{i,t})\phi_t - 1} \quad 0 < y_{i,t} < 1
$$

Under this parameterization, we have that

$$
\E{y_{i,t}} = \mu_{i,t} \quad 0 < \mu_{i,t} < 1; \quad  \text{and} \quad \Var{y_{i,t}} = \frac{\mu_{i,t}(1-\mu_{i,t})}{1 + \phi_t} \quad \phi_t > 0
$$

That is, for $Y_{i,t} \mid \boldsymbol{X}_{i,t} \overset{\text{indep.}}{\sim} \text{Beta}(\mu_{i,t}, \phi_t)$, we estimate a unique mean response $\mu_{i,t}$ for each sample location and time point, while assuming a shared precision parameter $\phi_t$ across locations within a given time. This is a common modeling assumption in generalized regression frameworks to reduce complexity and avoid overparameterization [@ferrari2004].

## The Forward Model
In the forward model, we estimated the parameter $\mu_{i,t}$ under a non-linear GLM framework:

$$
\E{y_{i,t}| y_{i,t-1}, \boldsymbol\theta_t} = \mu_{i,t} = \logit^{-1}(\eta_{i,t})
$$
and we specified the mean-structure of the model as

$$
\eta_{i,t} = \beta+ \delta y_{i,t-1}(1-y_{i,t-1}) + \gamma\sum_{j \neq i}\bigpar{y_{j,t-1}w_{ij} (d_{ij} + d_0)^{-\kappa}}
$${#eq-meanmod}

We then optimized the parameter vector $\boldsymbol\theta_{t,s,b}$ separately for each transition from time $t - 1$ to time $t$ and for each treatment-replicate combination. Optimization was performed using the quasi-Newton method with gradient-based Hessian approximation, as implemented in the `optim()` function (`method = "BFGS"`) in `R`. Additional details on covariate formatting and parameter initialization can be found in '00a_ModelingConsiderations.qmd`. 

::: {#tbl-covars}
\begin{table}
    \small
    \centering
    \subcaptionbox{Variable definitions for the proposed model.\label{tbl-vars}}{
        \begin{tabularx}{\textwidth}{lX}
            \toprule
            Variable & Description \\
            \midrule
            $y_{i,t-1}$ & Proportion of diseased plant tissue at survey unit $i$ in the previous time point. \\
            $y_{j,t-1}$ & Proportion of diseased plant tissue at survey unit $j$ in the previous time point. \\
            $w_{ij}$    & Wind vector on $i - j$ direction at the prior time point. \\
            $d_{ij}$    & Distance between survey unit $i$ and $j$. \\
            $d_0$       & A constant (optional) distance offset to avoid division errors at 0. \\
            \bottomrule
        \end{tabularx}
    }
    
    \vspace{1em}  

    \subcaptionbox{Model parameters and interpretations from the proposed model.\label{tbl-params}}{
        \begin{tabularx}{\textwidth}{lX}
            \toprule
            Parameter & Interpretation \\
            \midrule
            $\beta$  & Baseline log-odds of disease, after accounting for autoinfection and disease spread. \\
            $\delta$ & Change in log-odds of disease associated with autoinfection for each survey unit. \\
            $\gamma$ & Distance-adjusted change in log-odds of disease associated with disease spread from other survey units, after accounting for autoinfection. \\
            $\kappa$ & Dispersal parameter providing distance adjustment to change in log-odds of disease associated with individual sources; scales latter non-linearly with distance away from target. \\
            \bottomrule
        \end{tabularx}
    }
\end{table}

\small Covariates, parameters, and their interpretations for the proposed model from @eq-meanmod.
:::

## Introducing a Latent Structure

The ultimate goal of this project is to derive and implement a modeling framework for *source detection*. As a result of working with continuous intensity data, we were conveniently able to consider every plant where $j \neq i$ as a potential source of infection in the forward model. We explicitly accounted for the amount of inoculate moved from plant $j$ to plant $i$ via an orthogonal wind vector $w_{ij}$ as a non-linear function of the distance between plants through the dispersal component of the model (@eq-dispersal). 

$$
\gamma\sum_{j \neq i}\bigpar{y_{j,t-1}w_{ij} (d_{ij} + d_0)^{-\kappa}}
$${#eq-dispersal}

We weighted the contribution of each source by its severity at the previous time point $y_{j, t-1}$, and summed over the contribution from all other sources such that the dispersal term $\gamma$ can then be interpreted as in @tbl-covars. This approach has a major advantage in that we do not need to optimize the weight associated with each source $j \neq i$, which would certainly lead to issues of identifiability otherwise. The model falls short, however, when it comes to the issue of *source detection*, when we are concerned with the likelihood that plant $i$ was infected by plant $j \neq i$. 

@ojwang2021 propose a method in the context of their wavefront model in which they introduce a latent process $Z$ which indicates the causal attribution of disease to one of the $s \in \bigpar{1, \ldots, S}$ sources with a certain probability:

$$
Z \sim \text{Multinomial}\bigpar{1, \bigpar{p^{(1)}, \ldots, p^{(s)}}}
$$
Under this framework $P(Z = 1) = p^{(1)}$ indicates that an infection event is caused by source 1 with probability $p^{(1)}$." They then assume that a disease occurrence is described by each of the $S$ velocity models derived in the paper. Finally, although their approach assumes infection from a single source, they are able to estimate $p^{(1)}, \ldots, p^{(s)}$ using an EM algorithm to obtain an probabilistic interpretation of infection from each of the $S$ potential sources. Here, we propose a similar approach--motivated by the forward-model in @eq-meanmod.

## Backward Model

As in @ojwang2021, let us consider a latent variable $Z_i$ indicating the source of infection for plant $i$:

$$
Z_i \sim \text{Multinomial}(1, \boldsymbol{p}_i)
$$

Where 

  - $\boldsymbol{p}_i = \bigpar{p_{i1}, \ldots, p_{iS}}$
  - $p_{is} = P(Z_i = s)$
  - $\sum_{s=1}^Sp_{is} = 1$

Define the complete data as $\mathcal{X} = \bigbrace{\mathcal{Y}, \boldsymbol{Z}}$, where $\mathcal{Y} = \bigbrace{y_{i,t}, y_{j,t-1}, w_{ij}, d_{ij}}$ for all $j \neq i$. The complete-data log-likelihood is then given by:
$$
\ell(\boldsymbol{\theta} \mid \mathcal{X}) = \nsum \sum_{s=1}^S \indicate{Z_i = s} \cdot \log f(y_{i,t} \mid \mu_{i,t}^{(s)}, \phi_t)
$${#eq-loglik}

where $\mu_{i,t}^{(s)}$ denotes the predicted mean intensity at $i$ assuming infection from source group $s$. We can then apply the Expectation-Maximization (EM) algorithm to estimate the posterior source probabilities $\hat p^{(s)}$. At each iteration:

\textbf{E-step:} Use Bayes' rule to update
$$
\hat p_i^{(s)} =  P(Z_i = s \mid \mathcal{Y}) \propto f(y_{i,t} \mid \mu_{i,t}^{(s)}, \phi_t) \cdot \pi_s
$${#eq-estep}

Where $\pi_s$ is the prior probability that source group $C_s$ is responsible for infection at unit $i$. A uniform prior over all $S$ source groups is a natural choice: $\pi_s = 1/S$ for all $s$.

\textbf{M-step:} Maximize the expected complete-data log-likelihood
$$
Q(\boldsymbol\theta) = \nsum \sum_{s=1}^S \hat p_i^{(s)} \cdot \log f(y_{i,t} \mid \mu_{i,t}^{(s)}, \phi_t)
$${#eq-mstep}

This schematic can be made more complex by considering that dispersal dynamics may differ across source blocks $s \in S$. Here, we will assume that dispersal dynamics are constant across blocks. That is, we will continue to estimate a global parameter vector, $\boldsymbol\theta$ as opposed to a source-specific $\boldsymbol\theta^{(s)}$. 

Note that this new modeling framework requires a prior on the number of sources $S$. Here, we propose to assign each plant $i$ to one of $S$ evenly-divided and non-overlapping potential source groups $G_s \subset i \in \bigbrace{1, 2, \ldots, n}$ (@fig-sourcegroup). 

```{r}
#| echo: false
#| message: false
#| label: fig-sourcegroup
#| fig-align: center
#| fig-cap: "Schematics for each of the four grouping strategies considered in this study; corresponding to 16, 8, and 4 plants per source group from left to right."
#| fig-width: 8
#| cache: true

library(tidyverse)
library(here)
library(sf)

clusters <- readRDS(here("DataProcessed/experimental/clusters.rds"))

plant_clust <- bind_rows(clusters$stripe_4$stripe_assigned %>% mutate,
                         clusters$stripe_8h$stripe_assigned,
                         clusters$stripe_8v$stripe_assigned,
                         clusters$stripe_16$stripe_assigned)

grid <- bind_rows(clusters$stripe_4$grid,
                  clusters$stripe_8h$grid,
                  clusters$stripe_8v$grid,
                  clusters$stripe_16$grid)

plant_clust_sp <- plant_clust %>% 
  select(grid_id, grid_type, geometry) %>% 
  distinct()

grid %>% 
  ggplot()+
  geom_sf(fill = "transparent")+
  geom_sf_text(aes(label = grid_id))+
  facet_wrap(~grid_type, nrow = 1)+
  labs(x = "E", y = "N")+
  theme_classic()
```

At each iteration, we will specifically update $\hat\mu_{i,t}^{(s)}$ as

$$
\hat\mu_{i,t}^{(s)} = \logit^{-1}\bigpar{\hat\eta_{i,t}^{(s)}} = \hat\beta + \hat\delta y_{i,t-1}(1 - y_{i,t-1}) + \hat\gamma \sum_{j \in G_s} \bigpar{y_{j,t-1} w_{ij} (d_{ij} + d_0)^{-\hat\kappa}}
$${#eq-meanmod2}

where $\hat\cdot$ denotes the MLE estimates from the global model, with gradients updated to reflect $\hat p_i^{(s)}$ (@eq-newgrad - @eq-gradphi). Letting $y_{i,t}^* = \log\bigpar{\frac{y_{i,t}}{1 - y_{i,t}}}$ and $\mu_{i,t}^* = \psi(\mu_{i,t}^{(s)}\phi_t)-\psi((1-\mu_{i,t}^{(s)})\phi_t)$, we have that

$$
\frac{\partial Q}{\partial \mu_{i,t}^{(s)}} \times \frac{\partial \mu_{i,t}^{(s)}}{\partial\eta_{i,t}} \nsum \sum_{s=1}^S \hat p_i^{(s)} \cdot \phi_t(y_{i,t}^* - \mu_{i,t}^*) \cdot \mu_{i,t}^{(s)}(1 - \mu_{i,t}^{(s)})
$$ {#eq-newgrad}

Denoting the summand as $\text{grad}_{i,t}^{(s)}$, we can then write the updated gradients as 

$$
\begin{split}
\frac{\partial Q}{\partial\beta} &= \nsum \sum_{s=1}^S\text{grad}_{i,t}^{(s)} \\
\frac{\partial Q}{\partial\delta} &= \nsum \sum_{s=1}^S\text{grad}_{i,t}^{(s)}\times y_{i,t-1}(1 - y_{i,t-1}) \\
\frac{\partial Q}{\partial\gamma} &= \nsum \sum_{s=1}^S\text{grad}_{i,t}^{(s)} \times \sum_{j \in G_s}\bigpar{y_{j,t-1}w_{ij} (d_{ij} + d_0)^{-\kappa}} \\
\frac{\partial Q}{\partial\kappa} &= \nsum \sum_{s=1}^S\text{grad}_{i,t}^{(s)} \times -\gamma \sum_{j \in G_s}\bigpar{y_{j,t-1}w_{ij} (d_{ij} + d_0)^{-\kappa}\log(d_{ij} + d_0)}
\end{split}
$${#eq-newgrads}

and we can directly derive the new gradient for $\phi_t$ as 

$$
\frac{\partial Q}{\partial \phi_t} = \nsum \sum_{s = 1}^S \hat p_i^{(s)} \bigbrak{\psi(\phi_t) - \mu_{i,t}^{(s)} \psi(\mu_{i,t}^{(s)} \phi_t) - (1 - \mu_{i,t}^{(s)}) \psi(\phi_t(1 - \mu_{i,t}^{(s)})) + \mu_{i,t}^{(s)} \log y_{i,t} + (1 - \mu_{i,t}^{(s)}) \log (1 - y_{i,t})}
$${#eq-gradphi}

Initial estimates for $\boldsymbol\theta$ will be the estimated MLEs from the forward model. 
\newpage

# References
::: {#refs}
:::