---
title: "Spread of Wheat Stripe Rust in an Experimental Framework"
subtitle: "Preliminary Results: A Model for Source Detection Using EM-algorithm"
author:   
  - name: Trent VanHawkins
    affiliations:
      - ref: osu
    degrees: MS
    corresponding: true
  - name: Christopher Mundt
    affiliations:
      - ref: osu
    degrees: PhD
  - name: David Gent
    affiliations:
      - ref: usda
      - ref: osu
    degrees: PhD
  - name: Shirshendu Chatterjee
    affiliations:
      - ref: nyu
    degrees: PhD
  - name: Sharmodeep Bhattacharyya
    affiliations:
      - ref: osu
    degrees: PhD
affiliations:
  - id: osu
    name: Oregon State University
  - id: usda
    name: U.S. Department of Agriculture
  - id: nyu
    name: City University of New York
format: 
  html:
    lightbox: auto
embed-resources: true
toc: true
code-fold: true
execute: 
  warning: false
code-links:
  - text: GitHub Repository
    href: https://github.com/hawktre/wheat_striperust
page-layout: full
references: references.bib
bibliography: references.bib
---

# Introduction

Previous reports for this project have documented the development and implementation of a model for the spread of Stripe Rust (*Puccinia striiformis*) among Wheat plants, using infection data collected from an experimental study conducted between April and July of 2024 at the Hyslop Crop Science Field Laboratory in Benton County, Oregon. The reports in the table below will recall the work that has been accomplished up to this point in chronological order.

| Report Name | Description |
|----------------------------|--------------------------------------------|
| 00_EDA | Exploratory Data Analysis |
| 00a_ModelingConsiderations | Modeling framework and derivations for non-linear Beta regression, accounting for zero-inflation |
| 04_ModelResults_Hurdle_logistic | Preliminary modeling results for the spread of the disease |
| 05a_SourceDetection_ModelConsiderations | Modeling framework and derivations for a source-detection model built upon the forward model. |

The remaining reports found in the 'reports' folder document incremental steps in the modeling procedure that culminate in the work produced in `04_ModelREsults_Hurld_logistic`.

In the previous report, 05a_SourceDetection_ModelConsiderations, we introduced a framework for source detection (also referred to as a 'backwards model') by leveraging the optimized model parameters from the 'forward' model in an Expectation-Maximization (EM) optimization scheme. Here, we present the initial results for this method using the present dataset.

# Methods

We have extensively documented exploratory analyses and model derivations in previous reports. Here, we briefly highlight those aspects of experimental design and model development which are essential to interpreting source-detection results.

## Experimental Design

This experiment was conducted between the months of April and July of 2024 at the Hyslop Crop Science Field Laboratory in Benton County, Oregon. Wheat was planted in one of four blocks (labeled A-D), each containing three replicates (plots). Within each block, each $30.5 \times 30.5$ m plot was inoculated with spores from *Puccinia stiiformis* at one, two, or four locations of equal size ($0.76 \times 0.76$ m) between April 9th and April 25th, 2024. After approximately one month, plots were surveyed weekly for **five** consecutive weeks beginning May 17th, 2024. At each survey, domain experts visually estimated disease prevalence in $1.52 \times 1.52$ m grids, expressed as a percentage (0-100) of infected plant tissue within the sampling grid. Individual sampling locations are distinguished by their distance from the plot origin in meters. Further details of the experimental design may be found on pages 6 & 7 of the EEID Project Grant.

## Data Acquisition, Cleaning, and Exploration

Survey data, along with inoculum locations were provided by Chris Mundt. Additional data capturing wind speed (mph) and direction (degrees azimuth) were acquired from a local weather station \<1 km from the survey locations at a 15-minute resolution for the duration of the study period.

## Backward Model

As in @ojwang2021, Let us introduce a latent process $Z$ which indicates the causal attribution of disease to one of $k \in \big(1, \ldots, K\big)$ sources with a certain probability:

$$
Z_i \sim \mathrm{Multinomial}\big(1, \boldsymbol{\pi}\big)
$$ 

Recall from the forward model that our goal is to find the MLE $\hat{\boldsymbol\theta} = \big(\hat\alpha_t, \hat\mu_{it}, \hat\phi_t)$ at each time step $t$. We accomplish this by maximizing the marginal log-likelihood of our *observed* data, which we assume follows $\mathrm{ZIB}(y_{i} \mid \boldsymbol\theta)$. Note, however, that what we have observed is the joint distribution, $f(y_{i},z_{i})$. That is, the marginal log-likelihood is given by

$$
\ell(\boldsymbol\theta) = \sum_i\log\mathrm{ZIB}(y_{i}\mid \boldsymbol\theta) = \sum_i\log\left(\sum_z f(y_{i},z_{i})\right) = \sum_i\log\left(\sum_z \mathrm{ZIB}(y_{i}\mid \boldsymbol\theta) \cdot f(z_{i} \mid \boldsymbol\theta)\right)
$$

This log-likelihood is intractible; however, we can easily optimize a lower bound for it by leveraging the Expectation-Maximization (EM) algorithm. Letting $\Theta = \left(\boldsymbol\theta, \boldsymbol\pi\right)$ we can characterize this lower bound without loss of generality as

$$
\begin{split}
Q(\Theta; \Theta^{(h)}) &= \mathbb{E}_z\left[\sum_i\log f(y_{i}, z_{i} \mid \Theta)\right] \\
&= \sum_i \mathbb{E}_z\left[\log f(y_{i} \mid z_{i}, \boldsymbol\theta) f(z_{i}\mid \boldsymbol \pi)\right] \\
&= \sum_i \mathbb{E}_z\left[\log f(y_{i} \mid z_{i}, \boldsymbol\theta)\right] + \mathbb{E}_z\left[\log f(z_{i}\mid \boldsymbol \pi)\right] \\
&= \sum_i\sum_k p_{ik}^{(h)}\log \left(f(y_{i} \mid z_{i})\pi_k\right)
\end{split}
$$

where $p_{ik} = p(z_{i} = k \mid y_i, \Theta^{(h)})$, the posterior probability that sample location $i$ was infected by source $k$ given the observed data. Notice also, that we must characterize $f(y_{i} \mid z_{i} = k)$. Here, we propose that 

$$
y_i \mid z_i \overset{ind}{\sim} ZIB(\alpha, \mu_i^{(k)}, \phi^{(k)})
$$

Clearly, we need to adapt our forward model for the source-specific $\mu_i^{(k)}, \phi^{(k)}$. Specific to the setup of the present experiment, let us propose $k = 1, \ldots, K$ non-overlapping spatial arrangements of potential source groups (@fig-sourcegroup), denoted $G_k = \{i: x_i, y_i \in k\}$. 

```{r}
#| echo: FALSE
#| label: fig-sourcegroup
#| fig-align: center
#| fig-cap: "Schematics for each of the four grouping strategies considered in this study; corresponding to 16, 8, 4, and 1 plant(s) per source group from left to right."
#| fig-width: 8
#| fig-height: 3

library(here)
library(tidyverse)
library(sf)


spat_groups <- readRDS(here("DataProcessed/experimental/grids_sp.rds"))

grids <- rbind(
  spat_groups$`4`$grid,
  spat_groups$`8h`$grid,
  spat_groups$`8v`$grid,
  spat_groups$`16`$grid,
  spat_groups$`64`$grid
) %>% 
  mutate(k_label = factor(case_when(name == "2 x 2" ~ "k = 16",
                             name == "4 x 2" ~ "k = 8 (Horizontal)",
                             name == "2 x 4" ~ "k = 8 (Vertical)",
                             name == "4 x 4" ~ "k = 4",
                             name == "8 x 8" ~ "k = 64"), 
                          levels = c("k = 4", 
                                     "k = 8 (Horizontal)", 
                                     "k = 8 (Vertical)",
                                     "k = 16",
                                     "k = 64"))) 

points <- rbind(
  spat_groups$`4`$points,
  spat_groups$`8h`$points,
  spat_groups$`8v`$points,
  spat_groups$`16`$points,
  spat_groups$`64`$points
)

ggplot()+
  geom_sf(data = grids, fill = "transparent")+
  geom_sf(data = points)+
  facet_wrap(~k_label, nrow = 1)+
  theme_classic()+
  labs(x = "East (m)", y = "North (m)")

```

We then adapt the model of disease spread as 

$$
\frac{\mu_i^{(k)}}{1- \mu_i^{(k)}} = \beta^{(k)} + \delta^{(k)}  y_{i,t-1}(1 - y_{i,t-1}) + \gamma^{(k)}  \sum_{(j \neq i) \in G_k} \left(y_{j,t-1} w_{ij} (d_{ij} + d_0)^{-\kappa^{(k)}}\right)
$${#eq-meanmod}

and estimate $\phi^{(k)}$ concurrently via gradient descent. Next, we explicitly state the relevant steps for the EM alrogithm. 

## EM Algorithm Implementation
### Parameter Initializations

We initialized $\boldsymbol\tau = \left(\beta, \delta, \gamma, \kappa \right)$ using the MLE estimates from the forward model. We similarly conducted a sensitivity analysis using the initialization scheme proposed in `00a_model_considerations`. We initialized $\pi_k = \frac{1}{k}$ as the uniform prior. 

### E-Step 

Use Bayes' rule to update 

$$
p_{ik}^{(h + 1)} = \frac{f(y_i \mid z_i, \mu_i^{(k)}, \phi^{(k)}) \cdot \pi_k}{\sum_kf(y_i \mid z_i, \mu_i^{(k)}, \phi^{(k)}) \cdot \pi_k}
$${#eq-estep}

and the result to compute 

$$
Q(\Theta)^{(h + 1)} = \sum_i\sum_k p_{ik}\log \left(f(y_{i} \mid z_{i} = k) \cdot \pi_k\right)
$$

### M-step
For each component $k \in 1, \ldots, K$, update the parameter vector 

$$
\Theta^{(h + 1)} = \arg\max_\theta \ Q(\Theta | \Theta^{(h)})
$${#eq-mstep}

This can be accomplished using a variety of techniques for numerical approximation. For the present study, we utilized quasi-Newtonian Gradient Descent as implemented in `optim(method = 'BGFS')` in `r version$version.string`. Gradient derivations and details are available in `05a_SourceDetection_ModelConsiderations`. The MLE for $\boldsymbol\pi$ can be computed directly as

$$
\pi_k^{(h +1)} = \frac{\sum_{i = 1}^n p_{ik}^{(h)}}{n}
$$

### Convergence
We repeat the E- and M-step(s) until some convergence criteria is met. For the present study, we monitor both the Q-function and the posterior probabilities for sufficiently small changes. Appropriate convergence criteria are problem-specific in general. 

## Prediction

The goal of this study is to correctly determine which component $k$ contains the true source. What we have from the converged algorithm is an $n \times K$ matrix $\mathbf{p}$ whose individual entries denote the probability that sample location $i$ was infected by component $k$. To achieve a single prediction, we start with a soft-aggregation

$$
S_{kk} = \frac{1}{||G_k||}\sum_{i \in G_k}p_{ik}
$$
Thus, $\mathbf{S}$ will be a $K \times K$ matrix where the diagonal entries are the probability of self-infection for component and the off-diagonal entries are the probability of cross-infection. A single prediction can then be obtained by taking 

$$
\hat k = \arg\max_{k_1,k_2} \mathbf{S}
$$

### Prediction Error

From our prediction, we can compute a standard suite of multi-class prediction metrics. Traditional mutliclass metrics are produced from confusion matrices, where a *correct* prediction only occurs when the predicted class label matches the true class label. In this case, this approach may not produce a realistic, interpretable metric. To counter that, we propose a distance-weighted accuracy. Let $d_{\text{pred}}$ denote the distance from the centroid of the predicted source to the centroid of the true source and $d_{\text{max}}$ be the distance of the furthest centroid from the true source. Define the score for an individual prediction as

$$
e = 1 - \frac{d_{\text{pred}}}{d_{\text{max}}}
$$
Using this formula we have in general that $0 \leq e \leq 1$, so that we can interpret the metric similarly to standard accuracy. 

# Results

# References
::: {#refs}
:::
